version: '3.8'
services:
  km2:
    image: obsidiandynamics/kafdrop:latest
    hostname: kafdrop
    container_name: kafdrop
    environment:
      - KAFKA_BROKERCONNECT=${KAFKA_BROKERCONNECT}
        #    networks:
        #      - kfk-zkp-net
    ports:
      - "9000:9000"

        #networks:
        #  kfk-zkp-net:
        #    name: kfk-zkp-net
        #    driver: bridge

